
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-courses-s26-03
owner: ucsb-cs156-s26
repo_name: proj-courses-s26-03
pull_requests: [{"author":{"id":"MDQ6VXNlcjMwMzkwOTg2","is_bot":false,"login":"applebee1558","name":"Alex Liu"},"headRefName":"integrate-enrollmenthistory-frontend","number":30,"title":"Integrate enrollmenthistory to CourseDetailsIndexPage","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-03/pull/30"},{"author":{"id":"MDQ6VXNlcjMwMzkwOTg2","is_bot":false,"login":"applebee1558","name":"Alex Liu"},"headRefName":"add-enrollmenthistory-frontend","number":29,"title":"Add enrollmenthistory frontend","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-03/pull/29"},{"author":{"id":"MDQ6VXNlcjMwMzkwOTg2","is_bot":false,"login":"applebee1558","name":"Alex Liu"},"headRefName":"add-enrollmenthistory-api-backend","number":28,"title":"Add enrollment history controller, repository, and tests","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-03/pull/28"},{"author":{"id":"MDQ6VXNlcjM5MDM1Njg0","is_bot":false,"login":"kalyanrajavaram","name":""},"headRefName":"kr-ge-search","number":22,"title":"Added General Education Page Search","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-03/pull/22"},{"author":{"id":"MDQ6VXNlcjUzOTgxMDM3","is_bot":false,"login":"Hrithik-M","name":""},"headRefName":"download-form","number":21,"title":"Feature: Download Form for Course Data","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-03/pull/21"},{"author":{"id":"U_kgDOCNn2aA","is_bot":false,"login":"alexandrugherghescu01","name":""},"headRefName":"alexandrugherghescu01_17","number":20,"title":"Add Summer session column to course-over-time section table","url":"https://github.com/ucsb-cs156-s26/proj-courses-s26-03/pull/20"}]
